theme: jekyll-theme-cayman

baseurl: "/simple-airports-analysis"

plugins:
  - jekyll-relative-links
  - github-pages

relative_links:
  enabled: true
  collections: false

exclude:
  - 'dbt/models/overview.md'
  -  venv/

include:
  - README.md