theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
  - github-pages

relative_links:
  enabled: true
  collections: true

exclude:
  - 'dbt/models/overview.md'
  -  venv/

include:
  - README.md