version: 2


models:
  - name: base_airports
    description: |
      The cleaned version of `raw_airports`.

      _Note: The default materialisation of this table is `ephemeral`,
      but it is overridden in the SQL to be materialised as a `table` instead.
      This is so that indexes can be assigned._

    columns:
      - name: airport_id
        description: "Unique OpenFlights identifier for this airport."
        tests:
          - not_null

      - name: name
        description: "Name of airport. May or may not contain the City name."
      
      - name: city
        description: "Main city served by airport. May be spelled differently from Name."

      - name: country
        description: >
          Country or territory where airport is located.
          See [Countries](https://openflights.org/data.html#country) to cross-reference to ISO 3166-1 codes.

      - name: iata
        description: "3-letter IATA code. `Null` if not assigned/unknown."

      - name: icao
        description: "4-letter ICAO code. `Null` if not assigned."

      - name: latitude
        description: "Decimal degrees, usually to six significant digits. Negative is South, positive is North."

      - name: longitude
        description: "Decimal degrees, usually to six significant digits. Negative is West, positive is East."

      - name: altitude
        description: "In feet."

      - name: timezone
        description: |
          Hours offset from UTC.

          Fractional hours are expressed as decimals, eg. India is 5.5.

      - name: dst
        description: |
          Daylight savings time.

          One of E (Europe), A (US/Canada), S (South America),
          O (Australia), Z (New Zealand), N (None) or U (Unknown).

          See also: [Help: Time](https://openflights.org/help/time.html)

      - name: database_time_zone
        description: >
          Timezone in ["tz" (Olson) format](http://en.wikipedia.org/wiki/Tz_database),
          eg. "America/Los_Angeles".

      - name: type
        description: |
          Type of the airport.

          Value "airport" for air terminals, "station" for train stations,
          "port" for ferry terminals and "unknown" if not known.

          In this table, only type=airport is included.

      - name: source
        description: |
          Source of this data.

          "OurAirports" for data sourced from [OurAirports](http://ourairports.com/data/),
          "Legacy" for old data not matched to OurAirports (mostly DAFIF),
          "User" for unverified user contributions.

          In this table, only source=OurAirports is included.
